---
# ServiceAccount for kube-watcher
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-watcher
  namespace: default  # Change this to your target namespace

---
# Role with namespace-scoped permissions only
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-watcher
  namespace: default  # Change this to your target namespace
rules:
  # Core resources
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - secrets
      - events
    verbs:
      - list
      - watch
      - get

  # Apps resources
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs:
      - list
      - watch
      - get

---
# RoleBinding to bind the Role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-watcher
  namespace: default  # Change this to your target namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-watcher
subjects:
  - kind: ServiceAccount
    name: kube-watcher
    namespace: default  # Change this to your target namespace
