---
# Secret to store Slack webhook URL
# IMPORTANT: Replace the webhook URL with your actual Slack webhook
apiVersion: v1
kind: Secret
metadata:
  name: kube-watcher-secret
  namespace: default  # Change this to your target namespace
type: Opaque
stringData:
  slack-webhook-url: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
