apiVersion: v2
name: kube-watcher
description: Namespace限定権限で動作する軽量なKubernetesリソース監視Bot
type: application
version: 0.1.2
appVersion: "0.1.2"
keywords:
  - kubernetes
  - monitoring
  - slack
  - notifications
  - namespace-scoped
home: https://github.com/kqns91/kube-watcher
sources:
  - https://github.com/kqns91/kube-watcher
maintainers:
  - name: kube-watcher maintainers
    email: your-email@example.com
icon: https://raw.githubusercontent.com/kqns91/kube-watcher/main/docs/icon.png
