# デフォルト値
# helmfile や helm install 時に上書き可能

# レプリカ数
replicaCount: 1

# 監視対象のNamespace
# 注意: RBACもこのNamespaceに作成されます
namespace: default

# Dockerイメージ設定
image:
  repository: ghcr.io/kqns91/kube-watcher
  pullPolicy: IfNotPresent
  tag: "0.5.0"

# イメージプルシークレット（プライベートレジストリ使用時）
imagePullSecrets: []

# ServiceAccount名の上書き（空の場合は自動生成）
serviceAccountName: ""

# Pod annotations
podAnnotations: {}

# Pod Security Context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Container Security Context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true

# リソース制限
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Slack通知設定
slack:
  # Slack Webhook URL（直接指定する場合）
  webhookUrl: ""

  # 既存のSecretを使用する場合
  existingSecret: ""
  existingSecretKey: "webhook-url"

# 監視設定
config:
  # 監視するリソースタイプ
  resources:
    - kind: Pod
    - kind: Deployment
    - kind: Service

  # フィルター設定
  filters:
    - resource: Pod
      eventTypes:
        - ADDED
        - DELETED
        - UPDATED
      # ラベルフィルター（オプション）
      # labels:
      #   app: web
      #   environment: production

      # CEL式による高度なフィルタリング（v0.5.0以降、オプション）
      # expressionが設定されている場合、eventTypesとlabelsよりも優先されます
      # expression: 'event.eventType == "DELETED" && event.labels.app == "web"'

    - resource: Deployment
      eventTypes:
        - ADDED
        - DELETED
        - UPDATED

      # Deploymentの重複通知を除外する例
      # ReplicaSetUpdated と NewReplicaSetAvailable を除外
      # expression: 'event.eventType == "UPDATED" && event.reason != "ReplicaSetUpdated" && event.reason != "NewReplicaSetAvailable"'

    - resource: Service
      eventTypes:
        - ADDED
        - DELETED

  # 通知メッセージテンプレート
  # Go text/template形式
  # 利用可能な変数: .Kind, .Namespace, .Name, .EventType, .Timestamp, .Labels
  messageTemplate: |
    :kubernetes: *[{{ .Kind }}]* `{{ .Namespace }}/{{ .Name }}` が *{{ .EventType }}* されました
    時刻: {{ .Timestamp }}

  # イベント重複排除設定（オプション）
  deduplication:
    # 有効化/無効化（デフォルト: false）
    enabled: true

    # キャッシュエントリのTTL（秒単位、デフォルト: 300 = 5分）
    # この期間内に同じシグネチャのイベントは重複排除されます
    ttlSeconds: 300

    # 最大キャッシュサイズ（デフォルト: 1000）
    # 上限に達すると最も古いエントリが削除されます
    maxCacheSize: 1000

  # イベントバッチ処理設定（オプション）
  batching:
    # 有効化/無効化（デフォルト: false）
    enabled: false

    # バッチウィンドウの秒数（デフォルト: 300 = 5分）
    # 推奨範囲: 30-600秒
    windowSeconds: 300

    # バッチモード: detailed, summary, smart（デフォルト: smart）
    # detailed: すべてのイベントの詳細を表示
    # summary: イベント数のみを表示
    # smart: イベント数に応じて自動調整
    mode: smart

    # スマートモード設定
    smart:
      # グループごとの詳細表示する最大イベント数（デフォルト: 5）
      maxEventsPerGroup: 5

      # 全体の詳細表示する最大イベント数（デフォルト: 20）
      # これを超えるとサマリーモードに切り替わります
      maxTotalEvents: 20

      # 常に詳細を表示するイベントタイプ（デフォルト: DELETED）
      alwaysShowDetails:
        - DELETED

# RBAC設定
rbac:
  # RBACリソースを作成するかどうか
  create: true

  # 追加の権限ルール（必要に応じて）
  extraRules: []
  # - apiGroups: [""]
  #   resources: ["events"]
  #   verbs: ["list", "watch"]
