apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-watcher.fullname" . }}-config
  namespace: {{ include "kube-watcher.namespace" . }}
  labels:
    {{- include "kube-watcher.labels" . | nindent 4 }}
data:
  config.yaml: |
    namespace: {{ include "kube-watcher.namespace" . | quote }}

    resources:
    {{- range .Values.config.resources }}
      - kind: {{ .kind }}
    {{- end }}

    filters:
    {{- range .Values.config.filters }}
      - resource: {{ .resource }}
        eventTypes:
        {{- range .eventTypes }}
          - {{ . }}
        {{- end }}
        {{- if .labels }}
        labels:
          {{- toYaml .labels | nindent 10 }}
        {{- end }}
    {{- end }}

    notifier:
      slack:
        webhookUrl: {{ include "kube-watcher.slackWebhookUrl" . | quote }}
        template: {{ .Values.config.messageTemplate | quote }}

    {{- if .Values.config.deduplication }}
    deduplication:
      enabled: {{ .Values.config.deduplication.enabled }}
      {{- if .Values.config.deduplication.ttlSeconds }}
      ttlSeconds: {{ .Values.config.deduplication.ttlSeconds }}
      {{- end }}
      {{- if .Values.config.deduplication.maxCacheSize }}
      maxCacheSize: {{ .Values.config.deduplication.maxCacheSize }}
      {{- end }}
    {{- end }}

    {{- if .Values.config.batching }}
    batching:
      enabled: {{ .Values.config.batching.enabled }}
      {{- if .Values.config.batching.windowSeconds }}
      windowSeconds: {{ .Values.config.batching.windowSeconds }}
      {{- end }}
      {{- if .Values.config.batching.mode }}
      mode: {{ .Values.config.batching.mode | quote }}
      {{- end }}
      {{- if .Values.config.batching.smart }}
      smart:
        {{- if .Values.config.batching.smart.maxEventsPerGroup }}
        maxEventsPerGroup: {{ .Values.config.batching.smart.maxEventsPerGroup }}
        {{- end }}
        {{- if .Values.config.batching.smart.maxTotalEvents }}
        maxTotalEvents: {{ .Values.config.batching.smart.maxTotalEvents }}
        {{- end }}
        {{- if .Values.config.batching.smart.alwaysShowDetails }}
        alwaysShowDetails:
        {{- range .Values.config.batching.smart.alwaysShowDetails }}
          - {{ . }}
        {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
