{{- if and (not .Values.slack.existingSecret) .Values.slack.webhookUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-watcher.fullname" . }}-slack
  namespace: {{ include "kube-watcher.namespace" . }}
  labels:
    {{- include "kube-watcher.labels" . | nindent 4 }}
type: Opaque
stringData:
  webhook-url: {{ .Values.slack.webhookUrl | quote }}
{{- end }}
