name: Lint Helm Chart

on:
  pull_request:
    paths:
      - 'charts/**'
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Lint Helm Chart
        run: |
          helm lint charts/kube-watcher

      - name: Template Helm Chart
        run: |
          helm template test charts/kube-watcher \
            --set slack.webhookUrl="https://example.com/webhook" \
            --namespace test

      - name: Validate with kubeval (if available)
        continue-on-error: true
        run: |
          if command -v kubeval &> /dev/null; then
            helm template test charts/kube-watcher \
              --set slack.webhookUrl="https://example.com/webhook" \
              --namespace test | kubeval --strict
          else
            echo "kubeval not installed, skipping"
          fi
